### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by dullbananas** [another-elm/std#2]

**Comment by harrysarson** [comment]
Hi

**Comment by dullbananas** [comment]
What is purpose of another-elm

**Comment by harrysarson** [comment]
At the moment it doesn't really have a purpose. It is currently an experiment of mine which started out with a discussion on the elm-in-elm discord server about porting the elm runtime to another target.

The official elm standard packages are highly optimised for speed and small network size. I think there might be space for "another" set of standard packages which are instead optimised for correctness and readibility (practically both aims boil down to a minimum amount of kernel code).

The dream is for one day these standard packages to be a viable alternative to the standard ones (in a similar way to how musl has become a viable alternative to glibc). Currently, the packages are usable for headless applications but browser support is no where near there yet.

**Comment by dullbananas** [comment]
I am very shocked that you have been working on this so much despite not getting attention

**Comment by harrysarson** [comment]
I am finding it very interesting, we will see where it goes

**Comment by harrysarson** [comment]
Please reopen if there is anything actionable here!
